import { Raleway } from 'next/font/google'

import { Navbar } from './components/Navbar'

import '../globals.css'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'Lunar Commerce',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${raleway.className} w-full h-full min-h-screen bg-primary-100 dark:bg-primary-800 `}>
        {children}
      </body>
    </html>
  )
}
