'use client'

import { Raleway } from 'next/font/google'
import { AnimatePresence } from 'framer-motion'
import { Navbar } from '@/components/Navbar'
import { SessionProvider } from 'next-auth/react'

import '../globals.css'

import type { Metadata } from 'next'

const raleway = Raleway({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${raleway.className} w-full h-full min-h-screen bg-primary-100`}>
        <SessionProvider >
          <Navbar />
          <AnimatePresence mode="wait">{children}</AnimatePresence>
        </SessionProvider>
      </body>
    </html>
  )
}
