'use client'

import { Raleway } from 'next/font/google'
import { AnimatePresence } from 'framer-motion'

import { Navbar } from '@/components/Navbar'

import '../globals.css'

import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast'
import { PublicPageWrapper } from '@/components/PageWrapper/PublicPageWrapper'

const raleway = Raleway({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${raleway.className} w-full h-full min-h-screen bg-primary-100`}>
        <Toaster
          position="top-center"
          toastOptions={{
            className: 'text-sm',
            style: {
              color: '#325158'
            },
            duration: 3000,

            error: {
              position: 'bottom-center',
              style: {
                backgroundColor: '#fecaca',
                color: '#7f1d1d'
              }
            },
            success: {
              position: 'top-center',
              style: {
                backgroundColor: '#bbf7d0',
                color: '#14532a'
              }
            }
          }}
        />
        <Navbar />
        <AnimatePresence mode="wait">
          <PublicPageWrapper>{children}</PublicPageWrapper>
        </AnimatePresence>
      </body>
    </html>
  )
}
